let nombre = "Eduard";
let apellido = "Suarez";
let estudiante = `${nombre} ${apellido}`;
let estudianteMayus = estudiante.toUpperCase();
let estudianteMinus = estudiante.toLowerCase();
let cont = estudiante.length
let primerLetraNom = nombre[0];
let ultimaLetraAp = estudiante[estudiante.length-1];
let sinEspacios = estudiante.trim();
let estaNombre = estudiante.includes(nombre);